<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>The terrible hiring test</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                #text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Import</h1>
        <div> </div>
        <?php if ($res == true) : ?>
            <h2>Added  <?= htmlspecialchars($num_cat); ?> categories</h2>
            <h2>Added  <?= htmlspecialchars($num_auth); ?> authors</h2>
            <h2>Added  <?= htmlspecialchars($num_books); ?> books</h2>
        <?php endif; ?>
    </body>
</html>
