<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>The terrible hiring test</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                #text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
        <script src="/js/jquery-v1.8.2.min.js" type="text/javascript" language="javascript"></script>
        <script src="/js/app.js" type="text/javascript" language="javascript"></script>
    </head>
    <body>
        <h1>Test</h1>
        <div> </div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p><a href="/import">Import data</a>
            <p><a href="/table">The wonderful library</a>
            
        <?php endif; ?>
    </body>
</html>
